config/routes.rb
ErstiweAnmeldung::Application.routes.draw do
devise_for :users, :controllers => {:registrations => 'registrations'}, :path => ''
  devise_for :waitings, :controllers => {:registrations => 'waitings_registrations', :confirmations => 'waitings'}, :path => 'waiting_list'
  root :to => 'landing_page#index'

  devise_scope :user do
    get "users/list", :to => "registrations#list"
    get "edit_credentials", :to => "registrations#edit_email_password"
    get "users/:id/edit", :to => "registrations#edit", as: :edit_user
    delete "users/:id/erase", :to => "registrations#erase", as: :erase_user
    delete "waiting_list/:id/", :to => "waitings_registrations#destroy", as: :destroy_waiting
  end

  devise_scope :waiting do
    get "waiting_list/", :to => "waitings_registrations#new"
    get "waiting_list/list", :to => "waitings_registrations#list"
    get "waiting_list/closed", :to => 'landing_page#index', as: :waitings
    post "waiting_list/mass_add", :to => "waitings_registrations#mass_add"
    post "waiting_list/mail", :to => "waitings_registrations#mail", as: :waiting_mail    
  end

  get 'tickets/print'
  post 'tickets/generate' => 'tickets#generate'

  get 'app_config' => 'app_config#edit'
  patch 'app_config' => 'app_config#update'
  get 'app_config/reset_mail' => 'app_config#registration_complete_mail'
  get 'app_config/reset_mail_hard' => 'app_config#registration_complete_mail_hard_reset'
  post 'app_config/toggle_waiting_list' => 'app_config#toggle_waiting_list'

  

end

app/views/shared/_error_messages.html.erb
<% if object != nil and object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.haml
%ul{class:"inline-list"}
  - if devise_mapping.registerable? && controller_name != 'registrations'
    %li
      = link_to "Ticket einlösen", new_registration_path(resource_name)

  -if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    %li
      = link_to "Passwort vergessen?", new_password_path(resource_name) 

  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    %li
      = link_to "Keine Bestätigungsmail erhalten?", new_confirmation_path(resource_name) 

  - if controller_name != 'sessions'
    %li
      = link_to "Einloggen", new_session_path(resource_name)
      um Daten zu ändern