config/routes.rb
ErstiweAnmeldung::Application.routes.draw do
devise_for :users, :controllers => {:registrations => 'registrations'}, :path => ''
  devise_for :waitings, :controllers => {:registrations => 'waitings_registrations', :confirmations => 'waitings'}, :path => 'waiting_list'
  root :to => 'landing_page#index'

  devise_scope :user do
    get "users/list", :to => "registrations#list"
    get "edit_credentials", :to => "registrations#edit_email_password"
    get "users/:id/edit", :to => "registrations#edit", as: :edit_user
    delete "users/:id/erase", :to => "registrations#erase", as: :erase_user
    delete "waiting_list/:id/", :to => "waitings_registrations#destroy", as: :destroy_waiting
  end

  devise_scope :waiting do
    get "waiting_list/", :to => "waitings_registrations#new"
    get "waiting_list/list", :to => "waitings_registrations#list"
    get "waiting_list/closed", :to => 'landing_page#index', as: :waitings
    post "waiting_list/mass_add", :to => "waitings_registrations#mass_add"
    post "waiting_list/mail", :to => "waitings_registrations#mail", as: :waiting_mail    
  end

  get 'tickets/print'
  post 'tickets/generate' => 'tickets#generate'

  get 'app_config' => 'app_config#edit'
  patch 'app_config' => 'app_config#update'
  get 'app_config/reset_mail' => 'app_config#registration_complete_mail'
  get 'app_config/reset_mail_hard' => 'app_config#registration_complete_mail_hard_reset'
  post 'app_config/toggle_waiting_list' => 'app_config#toggle_waiting_list'

  

end

app/models/waiting.rb
class Waiting < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable, :confirmable
  attr_accessor :mail_text

  before_validation :deny_entry_if_waiting_list_closed

  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: email_regexp }

  scope :confirmed, -> { where("confirmed_at < ?",Time.now) }
  scope :unconfirmed, -> { where(confirmed_at: nil) }

  def send_on_create_confirmation_instructions
    unless @raw_confirmation_token
      generate_confirmation_token!
    end

    send_devise_notification(:waiting_list_confirmation_instructions, @raw_confirmation_token, {})
  end

  def deny_entry_if_waiting_list_closed
    AppConfig.first.waiting_list_open
  end    

end

app/controllers/waitings_controller.rb
class WaitingsController < Devise::ConfirmationsController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :edit_email_password, :update, :destroy, :list, :cancel]

  protected

    # The path used after confirmation.
    def after_confirmation_path_for(resource_name, resource)
      root_path
    end
end

app/controllers/waitings_registrations_controller.rb
class WaitingsRegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  # prepend_before_filter :authenticate_scope!, :only => [:edit, :edit_email_password, :update, :destroy, :list]
  before_filter :admin!, :only => [:list, :destroy]

  def mass_add
    params[:addresses].lines.each do |address|
      Waiting.create(email: address)
    end
    redirect_to waiting_list_list_path
  end

  def list
  end

  def mail
    WaitingMailer.mass_mail
    redirect_to waiting_list_list_path
  end

  # DELETE /resource
  def destroy
    @waiting = Waiting.find(params[:id])
    @waiting.destroy
    redirect_to waiting_list_list_path
  end

  private
    def admin!
      redirect_to new_user_session_path unless current_user && current_user.admin?
    end

end

app/views/waitings/waitings_registrations/list.html.haml
%div{class:"row"}
  %div{class:"small-9 large-centered columns"}
    %h2 Vorsicht! Diese Seite erst benutzen, wenn alle 70 Tickets eingelöst worden sind! Sonst kann es passieren, dass ein Ticket an mehrere Personen verteilt wird!
    %h2 Warteliste: #{(AppConfig.first.waiting_list_open == true ? "Geöffnet" : 'Geschlossen')} (#{(link_to (AppConfig.first.waiting_list_open == true ? "schliessen" : 'öffnen'), app_config_toggle_waiting_list_path, :method => :post).html_safe})

- replacements_count = User.withdrawn.count - User.from_waiting_list.count

%div{class:"row"}
  %div{class:"large-12 columns"}
    %h3 #{replacements_count} zurückgetretene(r) Mitfahrer.
    - if replacements_count > 0
      = button_to "Wartelistenpersonen frische Tickets zusenden", waiting_mail_path, method: :post, data: { confirm: "Sicher?" } 
%div{class:"row"}
  %div{class:"large-6 columns"}
    - if resource_class.confirmed.count > 0
      %h3 Wartelistenplätze
      %table
        %thead
          %tr
            %th Aktion
            %th Nr.
            %th E-Mail
        %tbody  
          - i = 0
          - resource_class.all.each do |waiting_user|
            - if waiting_user.confirmed?
              %tr
                %td
                  = link_to "×", destroy_waiting_path(waiting_user), :data => { :confirm => "Sicher?" }, :method => :delete
                %td
                  = i+=1
                %td
                  = waiting_user.email
    - else
      %p Niemand auf der Warteliste (#{resource_class.unconfirmed.count} unbestätigt)

  %div{class:"large-6 columns"}
    %label Funktioniert nur wenn Warteliste offen! Mehrere Adressen zur Warteliste hinzufügen. Jede Zeile nur eine Adresse! Adressen müssen trotzdem bestätigt werden.
    = form_tag(waiting_list_mass_add_path) do
      = text_area_tag 'addresses'
      = submit_tag 'Eintragen', class: "button small radius"

app/views/waitings/waitings_registrations/new.html.haml
-if AppConfig.first.waiting_list_open == true
  %div{class:"row"}
    %div{class:"small-9 large-centered columns"}
      %h2 Auf der Warteliste eintragen

  %div{class:"row"}
    %div{class:"small-6 large-centered columns"}
      %p Bla text

  = form_for(resource, :as => resource_name, :url => registration_path(resource_name), html:{class:"custom"}) do |f|

    %div{class:"row"}
      %div{class:"small-6 small-centered columns"}
        = f.label :email
        = f.email_field :email, class: error_class_for_resource(:email)
        - resource_errors(:email)
            

    %div{class:"row"}
      %div{class:"small-6 small-centered columns"}
        = f.submit "Ticket einlösen", class: "button expand radius success"

- else
  %div{class:"row"}
    %div{class:"small-9 large-centered columns"}
      %h2 Die Warteliste ist geschlossen.