config/routes.rb
ErstiweAnmeldung::Application.routes.draw do
devise_for :users, :controllers => {:registrations => 'registrations'}, :path => ''
  devise_for :waitings, :controllers => {:registrations => 'waitings_registrations', :confirmations => 'waitings'}, :path => 'waiting_list'
  root :to => 'landing_page#index'

  devise_scope :user do
    get "users/list", :to => "registrations#list"
    get "edit_credentials", :to => "registrations#edit_email_password"
    get "users/:id/edit", :to => "registrations#edit", as: :edit_user
    delete "users/:id/erase", :to => "registrations#erase", as: :erase_user
    delete "waiting_list/:id/", :to => "waitings_registrations#destroy", as: :destroy_waiting
  end

  devise_scope :waiting do
    get "waiting_list/", :to => "waitings_registrations#new"
    get "waiting_list/list", :to => "waitings_registrations#list"
    get "waiting_list/closed", :to => 'landing_page#index', as: :waitings
    post "waiting_list/mass_add", :to => "waitings_registrations#mass_add"
    post "waiting_list/mail", :to => "waitings_registrations#mail", as: :waiting_mail    
  end

  get 'tickets/print'
  post 'tickets/generate' => 'tickets#generate'

  get 'app_config' => 'app_config#edit'
  patch 'app_config' => 'app_config#update'
  get 'app_config/reset_mail' => 'app_config#registration_complete_mail'
  get 'app_config/reset_mail_hard' => 'app_config#registration_complete_mail_hard_reset'
  post 'app_config/toggle_waiting_list' => 'app_config#toggle_waiting_list'

  

end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController

  def index
  end

end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/views/landing_page/index.html.haml
%div{class:"row"}
  %div{class:"small-9 large-centered columns"}
    %h1 Anmeldung Erstiwochenende
%div{class:"row"}
  %div{class:"large-12 columns"}
    %p
      Herzlich Willkommen auf der Seite des Erstiwochenendes der Fachschaften
      %a{href:"https://geofs.uni-muenster.de/geoinf/", target:"_blank"} Geoinformatik
      &amp;
      %a{href:"https://geofs.uni-muenster.de/geoloek/", target:"_blank"} Geographie/Landschaftsökologie
      %br
      %br
      Hier kannst du das Ticket, das du beim Geobrunch&trade; erworben hast, einlösen.

- if !current_user
  %div{class:"row"}
    %div{class:"large-6 columns"}
      = link_to new_user_registration_path, class:"callout_panel_a" do
        %div{class:"panel callout radius"} Ich habe ein Ticket und möchte es einlösen!
    %div{class:"large-6 columns"}
      - if false
        = link_to waiting_list_path do
          %div{class:"panel radius"} Ich möchte auf die Warteliste!
  = link_to 'Einloggen', new_user_session_path