config/routes.rb
ErstiweAnmeldung::Application.routes.draw do
devise_for :users, :controllers => {:registrations => 'registrations'}, :path => ''
  devise_for :waitings, :controllers => {:registrations => 'waitings_registrations', :confirmations => 'waitings'}, :path => 'waiting_list'
  root :to => 'landing_page#index'

  devise_scope :user do
    get "users/list", :to => "registrations#list"
    get "edit_credentials", :to => "registrations#edit_email_password"
    get "users/:id/edit", :to => "registrations#edit", as: :edit_user
    delete "users/:id/erase", :to => "registrations#erase", as: :erase_user
    delete "waiting_list/:id/", :to => "waitings_registrations#destroy", as: :destroy_waiting
  end

  devise_scope :waiting do
    get "waiting_list/", :to => "waitings_registrations#new"
    get "waiting_list/list", :to => "waitings_registrations#list"
    get "waiting_list/closed", :to => 'landing_page#index', as: :waitings
    post "waiting_list/mass_add", :to => "waitings_registrations#mass_add"
    post "waiting_list/mail", :to => "waitings_registrations#mail", as: :waiting_mail    
  end

  get 'tickets/print'
  post 'tickets/generate' => 'tickets#generate'

  get 'app_config' => 'app_config#edit'
  patch 'app_config' => 'app_config#update'
  get 'app_config/reset_mail' => 'app_config#registration_complete_mail'
  get 'app_config/reset_mail_hard' => 'app_config#registration_complete_mail_hard_reset'
  post 'app_config/toggle_waiting_list' => 'app_config#toggle_waiting_list'

  

end

app/views/layouts/application.html.haml
!!! 5
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"
  
  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0, user-scalable=false;" }

  %title= content_for?(:title) ? yield(:title) : "ErstiweAnmeldung"

  -# Included CSS Files
  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true

  -# Included JS Files
  = javascript_include_tag "application", "data-turbolinks-track" => true

  = csrf_meta_tag

%body
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      :javascript
        setTimeout(function() { $('a.close').trigger('click'); }, 3000);
      %div{class:"row"}
        %div{class:"large-12 columns"}
          %div{ data: {alert: true}, class: "alert-box #{name} radius", id: "flash_#{name}" }
            = msg
            %a{ href: "#", class: "close" } &times;

  - if user_signed_in?
    %div{class:"row"}
      %div{class:"large-12 columns"}
        %ul{class:'inline-list'}
          %li
            = current_user.email #{"(admin)" if current_user.admin?}
          - if current_user.admin?
            %li
              = link_to 'Anmeldungsliste', users_list_path
            %li
              = link_to 'Warteliste', waiting_list_list_path
            %li
              = link_to 'Tickets ausdrucken', tickets_print_path
            %li
              = link_to 'Anmeldeseite konfigurieren', app_config_path
          - else
            %li
              = link_to 'Meine Daten', edit_user_registration_path
          %li
            = link_to 'Ausloggen', destroy_user_session_path, method: :delete

  %div{style:'clear:both;'}
  - if !content_for?(:override_width)
    %div{class:"row"}
      %div{class:"small-12 columns"}
        = yield
  - else
    = yield

  :javascript
    $(document).foundation();